### ISSUE TITLE
Peer to peer code review 

### ISSUE THREAD

**Issue by teekaytech** [teekaytech/Catalogue-of-Trivia-Questions#1]
Thank guys for listening.

Kindly drop your suggestions and comments here so I can keep track and implement them as appropriate :bow:

**Comment by mbabaliiryn** [comment]
hey, Taofeek congrats on what you have achieved within a short time.  In the categoryList file inside the container folder line 11
try  useEffect(() => {
    dispatch(fetchCategories());
  }, []);
Hope it will help you achieve what you what. Wish you the best of luck.

**Comment by mariosknl** [comment]
You have done a great job so far. Remember you use a function to format the data you are retrieving from the API.

**Comment by mariosknl** [comment]
I liked the way you solved your problems with the project Taofeek. Congrats my friend
